#######
### Minefest Server Configuration
### World-specific settings for network sync and testing
### CRITICAL: Boolean values must be lowercase (true/false)
### Examples: enableTestBroadcaster = true (NOT True)
###          debugMode = false (NOT False)
#######
["Server Configuration"]
	#Time synchronization interval in seconds
	#Range: 1 ~ 300
	syncInterval = 30
	#Enable test broadcaster (sends periodic test messages to all players)
	#Default: false (enable for development/testing, disable for production)
	enableTestBroadcaster = true
	#Whether this server is the time authority
	isTimeAuthority = false
	#Test broadcast interval in seconds
	#Range: 5 ~ 300
	broadcastInterval = 30
	#Enable debug logging
	debugMode = false
